# Generated by Django 5.1.6 on 2025-02-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_comment_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-time_of_creating"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
